* org-mode
  El modo Org (Org-mode) es un modo de edición del editor de texto Emacs mediante el cual se editan documentos jerárquicos en texto plano.

  Su uso encaja con distintas necesidades, como la creación de notas de cosas por hacer, la planificación de proyectos y hasta la escritura de páginas web. Por ejemplo, los elementos to-do (cosas por hacer) pueden disponer de prioridades y fechas de vencimiento, pueden estar subdivididos en subtareas o en listas de verificación, y pueden etiquetarse o dársele propiedades. También puede generarse automáticamente una agenda de las entradas de cosas por hacer.1​

  La mayor parte del comportamiento del modo Org puede personalizarse mediante los procedimientos habituales en Emacs (es decir estableciendo directamente el valor de las variables o utilizando la interfaz Customize, más amigable para los usuarios).

  Desde la versión 22 de Emacs, el modo Org es parte de su distribución oficial2​ - aunque también dispone de entregas separadas, con lo que las versiones más recientes del modo Org con respecto a la que se incluye en Emacs también están disponibles. 


** Integración
   El modo Org se puede integrar con

   + La BBDB de Emacs para enlazar con los detalles de contactos del usuario.
   + Navegadores Web como Firefox, para seguir URL.
   + El modo Remember para la toma rápida de notas e ideas, pensamientos o enlaces, y después editarlas, categorizarlas o ficharlas adecuadamente.
   + Los clientes de correo y noticias de Emacs, tales como Gnus, VM y Wanderlust, para enlazar con mensajes de correo o de noticias.
   + El teléfono móvil o celular a través de MobileOrg para:
     + Iphone/Ipod https://web.archive.org/web/20100323140800/http://mobileorg.ncogni.to/ y
     + Los teléfonos basados en Android https://web.archive.org/web/20100204115729/http://wiki.github.com/matburt/mobileorg-android/

   También se puede usar para editar esquemas en ficheros que no sean .org.

   (Algunas de las integraciones citadas requieren extensiones de terceros para el modo Org, siendo todas ellas Software Libre.) 

** Registro de problemas distribuido
   El modo Org se puede usar como un sistema distribuido de registro de problemas o fallos, si se almacenan los ficheros .org en un sistema de control de revisiones distribuido. Los desarrolladores de la extensión org-babel usan el modo Org de esta manera para registrar los informes de fallos y las solicitudes de características.

** Enlaces externos
   + [[https://www.orgmode.org/][Sitio web del modo Org]], básicamente en inglés
   + [[https://orgmode.org/worg/index.html][Lista de guías de texto y vídeo acerca del modo Org]] en el wiki del sitio, Worg, básicamente en inglés

